version: '3'

services:
  db:
    container_name: lawtech_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=lawtech
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lawtech_backend

#  pgAdmin:
#    restart: always
#    image: dpage/pgadmin4
#    ports:
#      - "5555:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: otakuctb1231999@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: otakuctb123
#    volumes:
#      - pgadmin:/var/lib/pgadmin


  web:
    container_name: lawtech_web
    build: .
    command: python manage.py runserver 0.0.0.0:5000 --nothreading --noreload
    #command: wget 112.137.142.8:9200
    #command: wget 112.137.142.8:9202
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    networks:
      - lawtech_backend
    depends_on:
      - db


volumes:
    pgdata:
#    pgadmin:

networks:
  lawtech_backend:
