# Generated by Django 3.0.2 on 2020-01-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=20)),
                ('created_time', models.DateTimeField()),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('enable', models.BinaryField(verbose_name=1)),
                ('last_update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('work_place', models.CharField(max_length=255)),
                ('last_update_time', models.DateTimeField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_time', models.IntegerField(verbose_name=11)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'unique_together': {('user_id', 'role_id')},
            },
        ),
    ]
